=== volen17/XML-Project-Effect-Pedals/effect_pedal_catalogue.dtd
<?xml version="1.0" encoding="UTF-8"?>
        <!ELEMENT effect_pedal_catalogue (effect_pedal+)>
        <!ELEMENT effect_pedal (image, name, type, year_of_manufacturing, price, power, dimensions, weight, true_bypass, description)>
        <!ELEMENT image (#PCDATA)>
        <!ELEMENT name (manufacturer_name, model_name)>
        <!ELEMENT manufacturer_name (#PCDATA)>
        <!ELEMENT model_name (#PCDATA)>
        <!ELEMENT type (#PCDATA)>
        <!ELEMENT year_of_manufacturing (#PCDATA)>
        <!ELEMENT price (#PCDATA)>
        <!ELEMENT power (polarity, voltage, current_draw, battery)>
        <!ELEMENT polarity (#PCDATA)>
        <!ELEMENT voltage (#PCDATA)>
        <!ELEMENT current_draw (#PCDATA)>
        <!ELEMENT battery (#PCDATA)>
        <!ELEMENT dimensions (width, height, length)>
        <!ELEMENT width (#PCDATA)>
        <!ELEMENT height (#PCDATA)>
        <!ELEMENT length (#PCDATA)>
        <!ELEMENT weight (#PCDATA)>
        <!ELEMENT true_bypass (#PCDATA)>
        <!ELEMENT description (text)>
        <!ELEMENT text (#PCDATA)>

        <!ATTLIST effect_pedal analog_or_digital (Digital|Analog) #IMPLIED>
        <!ATTLIST price currency CDATA #REQUIRED>
        <!ATTLIST battery has (Да|Не) #IMPLIED>
        <!ATTLIST width unit CDATA #REQUIRED>
        <!ATTLIST height unit CDATA #REQUIRED>
        <!ATTLIST length unit CDATA #REQUIRED>
        <!ATTLIST weight unit CDATA #REQUIRED>
        <!ATTLIST true_bypass has (Да|Не) #IMPLIED>

=== volen17/XML-Project-Effect-Pedals/mythos.xml
<?xml version="1.0" encoding="utf-8"?>

<!DOCTYPE effect_pedal_catalogue SYSTEM "effect_pedal_catalogue.dtd">

<effect_pedal_catalogue>
    <effect_pedal analog_or_digital="Analog">
        <image>mythos.jpg</image>
        <name>
            <manufacturer_name>Mythos</manufacturer_name>
            <model_name>Golden Fleece</model_name>
        </name>
        <type>Overdrive Fuzz</type>
        <year_of_manufacturing>2019</year_of_manufacturing>
        <price currency="лв.">326.97</price>
        <power>
            <polarity>- в средата</polarity>
            <voltage>9 DC</voltage>
            <current_draw>10mA</current_draw>
            <battery has="Не"/>
        </power>
        <dimensions>
            <width unit="см">4</width>
            <height unit="см">4,5</height>
            <length unit="см">9,2</length>
        </dimensions>
        <weight unit="гр">128</weight>
        <true_bypass has="Да"/>
        <description>
            <text>
                Педал, който реагира прекрасно на вашата динамика на свирене, което води до топъл, мъркащ овърдрайв. Звучи твърде добре, за да е истина, нали? Но Golden Fleece от Mythos наистина преодолява границата между fuzz и овърдрайв педала. Педалът има един контрол за основна сила на звука, така че целият контрол на тона и усилването идва от вас и вашата китара. Намалете силата на звука и тонът се изчиства веднага.
            </text>
        </description>
    </effect_pedal>
</effect_pedal_catalogue>

=== volen17/XML-Project-Effect-Pedals/eq_xml.xml
<?xml version="1.0" encoding="utf-8"?>
<?xml-stylesheet type="text/xsl" href="eq_xml.xsl"?>

<!DOCTYPE effect_pedal_catalogue SYSTEM "effect_pedal_catalogue.dtd">

<effect_pedal_catalogue>
    <effect_pedal analog_or_digital="Digital">
        <image>eq.jpg</image>
        <name>
            <manufacturer_name>Source Audio</manufacturer_name>
            <model_name>EQ2</model_name>
        </name>
        <type>Programmable Equalizer</type>
        <year_of_manufacturing>2020</year_of_manufacturing>
        <price currency="лв.">669.96</price>
        <power>
            <polarity>- в средата</polarity>
            <voltage>9 DC</voltage>
            <current_draw>180mA</current_draw>
            <battery has="Не"/>
        </power>
        <dimensions>
            <width unit="см">7</width>
            <height unit="см">5,1</height>
            <length unit="см">11,4</length>
        </dimensions>
        <weight unit="гр">280</weight>
        <true_bypass has="Да"/>
        <description>
            <text>
                По собствените думи на Source Audio, програмируемият еквалайзер EQ2 е „най-мощният и усъвършенстван еквалайзер на планетата“. Смело твърдение, но въз основа на впечатляващия си набор от функции - може и да е вярно! След оригиналния им програмируем EQ педал, използван от хора като Дейвид Гилмор и Джон Мейър, иновативният Source Audio EQ2 добавя още повече функционалност.
            </text>
        </description>
    </effect_pedal>
</effect_pedal_catalogue>

=== volen17/XML-Project-Effect-Pedals/compressors_html.xml
<?xml version="1.0"?>
<?xml-stylesheet type="text/xsl" href="compressors_html.xsl"?>

<!DOCTYPE effect_pedal_catalogue SYSTEM "effect_pedal_catalogue.dtd">

<effect_pedal_catalogue>
	<effect_pedal analog_or_digital="Analog">
		<image>cali76.jpg</image>
		<name>
			<manufacturer_name>Origin Effects</manufacturer_name>
			<model_name>Cali76 Compact Deluxe</model_name>
		</name>
		<type>Compressor</type>
		<year_of_manufacturing>2014</year_of_manufacturing>
		<price currency="лв.">632.78</price>
		<power>
			<polarity>- в средата</polarity>
			<voltage>9/18V DC</voltage>
			<current_draw>77/104mA</current_draw>
			<battery has="Не"/>
		</power>
		<dimensions>
			<width unit="см">14,3</width>
			<height unit="см">6,6</height>
			<length unit="см">6,5</length>
		</dimensions>
		<weight unit="гр">620</weight>
		<true_bypass has="Да"/>
		<description>
			<text>Cali76 се счита за един от най-добрите, ако не и най-добрия компресор, който се предлага на пазара днес. Педалът е проектиран, за да ви даде използваем, висококачествен компресор, без твърде много да се забърквате с копчета, които са трудни за разбиране.</text>
		</description>
	</effect_pedal>
</effect_pedal_catalogue>

=== volen17/XML-Project-Effect-Pedals/vemuram.xml
<?xml version="1.0" encoding="utf-8"?>

<!DOCTYPE effect_pedal_catalogue SYSTEM "effect_pedal_catalogue.dtd">

<effect_pedal_catalogue>
    <effect_pedal analog_or_digital="Analog">
        <image>vemuram.jpg</image>
        <name>
            <manufacturer_name>Vemuram</manufacturer_name>
            <model_name>Jan Ray</model_name>
        </name>
        <type>Overdrive</type>
        <year_of_manufacturing>2017</year_of_manufacturing>
        <price currency="лв.">844.49</price>
        <power>
            <polarity>- в средата</polarity>
            <voltage>9 DC</voltage>
            <current_draw>5mA</current_draw>
            <battery has="Да"/>
        </power>
        <dimensions>
            <width unit="см">7</width>
            <height unit="см">5</height>
            <length unit="см">11,2</length>
        </dimensions>
        <weight unit="гр">428</weight>
        <true_bypass has="Да"/>
        <description>
            <text>
                Jan Ray е проектиран да пресъздаде ударния ясен тон на усилвателите Blackface Fender от 60-те - така нареченият звук "Fender Magic 6". Лесен за управление овърдрайв, запазващ характеристиките на китарата със страхотен състейн без неестествена компресия.
            </text>
        </description>
    </effect_pedal>
</effect_pedal_catalogue>

=== volen17/XML-Project-Effect-Pedals/fuzzes_html.xml
<?xml version="1.0"?>
<?xml-stylesheet type="text/xsl" href="fuzzes_html.xsl"?>

<!DOCTYPE effect_pedal_catalogue SYSTEM "effect_pedal_catalogue.dtd">

<effect_pedal_catalogue>
    <effect_pedal analog_or_digital="Analog">
        <image>mythos.jpg</image>
        <name>
            <manufacturer_name>Mythos</manufacturer_name>
            <model_name>Golden Fleece</model_name>
        </name>
        <type>Overdrive Fuzz</type>
        <year_of_manufacturing>2019</year_of_manufacturing>
        <price currency="лв.">326.97</price>
        <power>
            <polarity>- в средата</polarity>
            <voltage>9 DC</voltage>
            <current_draw>10mA</current_draw>
            <battery has="Не"/>
        </power>
        <dimensions>
            <width unit="см">4</width>
            <height unit="см">4,5</height>
            <length unit="см">9,2</length>
        </dimensions>
        <weight unit="гр">128</weight>
        <true_bypass has="Да"/>
        <description>
            <text>
                Педал, който реагира прекрасно на вашата динамика на свирене, което води до топъл, мъркащ овърдрайв. Звучи твърде добре, за да е истина, нали? Но Golden Fleece от Mythos наистина преодолява границата между fuzz и овърдрайв педала. Педалът има един контрол за основна сила на звука, така че целият контрол на тона и усилването идва от вас и вашата китара. Намалете силата на звука и тонът се изчиства веднага.
            </text>
        </description>
    </effect_pedal>
    <effect_pedal analog_or_digital="Analog">
        <image>broadcast.jpg</image>
        <name>
            <manufacturer_name>Hudson Electronics</manufacturer_name>
            <model_name>Dual Broadcast</model_name>
        </name>
        <type>Germanium Preamp</type>
        <year_of_manufacturing>2015</year_of_manufacturing>
        <price currency="лв.">388.13</price>
        <power>
            <polarity>- в средата</polarity>
            <voltage>9-24 DC</voltage>
            <current_draw>20mA</current_draw>
            <battery has="Не"/>
        </power>
        <dimensions>
            <width unit="см">11,9</width>
            <height unit="см">5,5</height>
            <length unit="см">9,3</length>
        </dimensions>
        <weight unit="гр">366</weight>
        <true_bypass has="Да"/>
        <description>
            <text>
                Broadcast е германиев предусилвател клас-А, базиран на класическите конзоли за излъчване от 60-те години на миналия век. Broadcast може да покрие всичко от искрящо чисто усилване до прозрачен овърдрайв, всичко със здравословна доза сила на звука, която да накара вашия усилвател. Broadcast включва специално подбран трансформатор със стоманена сърцевина Triad и германиев транзистор. Увеличаването на усилването при излъчването започва да насища трансформатора и дискретната верига на педала, което води до нежна и динамична компресия, съчетана с фино удебеляване на средния диапазон. Когато превключвателят на усилването е във висока настройка и контролът на подстригването е изключен, Broadcast започва да издава по-тежки изкривени звуци с топла и размита граница към тях. Излъчването обхваща широк спектър от задвижени и изкривени тонове, като същевременно остава динамичен, реагирайки добре на атаката и фините нюанси на всеки изпълнител.
            </text>
        </description>
    </effect_pedal>
</effect_pedal_catalogue>

=== volen17/XML-Project-Effect-Pedals/broadcast.xml
<?xml version="1.0" encoding="utf-8"?>

<!DOCTYPE effect_pedal_catalogue SYSTEM "effect_pedal_catalogue.dtd">

<effect_pedal_catalogue>
    <effect_pedal analog_or_digital="Analog">
        <image>broadcast.jpg</image>
        <name>
            <manufacturer_name>Hudson Electronics</manufacturer_name>
            <model_name>Dual Broadcast</model_name>
        </name>
        <type>Germanium Preamp</type>
        <year_of_manufacturing>2015</year_of_manufacturing>
        <price currency="лв.">388.13</price>
        <power>
            <polarity>- в средата</polarity>
            <voltage>9-24 DC</voltage>
            <current_draw>20mA</current_draw>
            <battery has="Не"/>
        </power>
        <dimensions>
            <width unit="см">11,9</width>
            <height unit="см">5,5</height>
            <length unit="см">9,3</length>
        </dimensions>
        <weight unit="гр">366</weight>
        <true_bypass has="Да"/>
        <description>
            <text>
                Broadcast е германиев предусилвател клас-А, базиран на класическите конзоли за излъчване от 60-те години на миналия век. Broadcast може да покрие всичко от искрящо чисто усилване до прозрачен овърдрайв, всичко със здравословна доза сила на звука, която да накара вашия усилвател. Broadcast включва специално подбран трансформатор със стоманена сърцевина Triad и германиев транзистор. Увеличаването на усилването при излъчването започва да насища трансформатора и дискретната верига на педала, което води до нежна и динамична компресия, съчетана с фино удебеляване на средния диапазон. Когато превключвателят на усилването е във висока настройка и контролът на подстригването е изключен, Broadcast започва да издава по-тежки изкривени звуци с топла и размита граница към тях. Излъчването обхваща широк спектър от задвижени и изкривени тонове, като същевременно остава динамичен, реагирайки добре на атаката и фините нюанси на всеки изпълнител.
            </text>
        </description>
    </effect_pedal>
</effect_pedal_catalogue>

=== volen17/XML-Project-Effect-Pedals/timeline_plain_text.xml
<?xml version="1.0" encoding="utf-8"?>
<?xml-stylesheet type="text/xsl" href="timeline_plain_text.xsl"?>

<!DOCTYPE effect_pedal_catalogue SYSTEM "effect_pedal_catalogue.dtd">

<effect_pedal_catalogue>
    <effect_pedal analog_or_digital="Digital">
        <image>timeline.jpg</image>
        <name>
            <manufacturer_name>Strymon</manufacturer_name>
            <model_name>Timeline</model_name>
        </name>
        <type>Multidimensional Delay</type>
        <year_of_manufacturing>2016</year_of_manufacturing>
        <price currency="лв.">937.94</price>
        <power>
            <polarity>- в средата</polarity>
            <voltage>9 DC</voltage>
            <current_draw>300mA</current_draw>
            <battery has="Не"/>
        </power>
        <dimensions>
            <width unit="см">17,5</width>
            <height unit="см">5</height>
            <length unit="см">12,7</length>
        </dimensions>
        <weight unit="гр">880</weight>
        <true_bypass has="Да"/>
        <description>
            <text>
                Вероятно един от, ако не и най-обсъжданите педали за китарни ефекти на планетата, Strymon TimeLine със сигурност предизвиква шум! И така, за какво е цялата суматоха? TimeLine всъщност представлява 12 различни дилея в една кутия, съставена от прости цифрови дилеи през dTape и dBucket дилеи, взети от други педали на Strymon, чак до нови и безумни дилеи като Ice, Swell, Trem, Filter и LoFi. Ако се сетите за функция, която ще ви е необходима от дилей педал, TimeLine вече я има!
            </text>
        </description>
    </effect_pedal>
</effect_pedal_catalogue>

=== volen17/XML-Project-Effect-Pedals/lightspeed.xml
<?xml version="1.0" encoding="utf-8"?>

<!DOCTYPE effect_pedal_catalogue SYSTEM "effect_pedal_catalogue.dtd">

<effect_pedal_catalogue>
    <effect_pedal analog_or_digital="Analog">
        <image>lightspeed.jpg</image>
        <name>
            <manufacturer_name>Greer Amps</manufacturer_name>
            <model_name>Lightspeed</model_name>
        </name>
        <type>Organic Overdrive</type>
        <year_of_manufacturing>2018</year_of_manufacturing>
        <price currency="лв.">435.18</price>
        <power>
            <polarity>- в средата</polarity>
            <voltage>9 DC</voltage>
            <current_draw>11mA</current_draw>
            <battery has="Да"/>
        </power>
        <dimensions>
            <width unit="см">6,7</width>
            <height unit="см">5,5</height>
            <length unit="см">12</length>
        </dimensions>
        <weight unit="гр">268</weight>
        <true_bypass has="Да"/>
        <description>
            <text>
                Lightspeed е един от най-популярните педали от усилвателите на Greer и с добра причина! Звучи невероятно. Това е прозрачен овърдрайв, който е създаден специално да запази органичния звук на вашата китара, без да променя тоналността твърде много. Въпреки това, може да се настрои да „оцветява“ звука малко повече и да изтласка чист усилвател над ръба или да добави сладък състейн към вече крънчи канал.
            </text>
        </description>
    </effect_pedal>
</effect_pedal_catalogue>
