=== volen17/XML-Project-Effect-Pedals/effect_pedal_catalogue.dtd
<?xml version="1.0" encoding="UTF-8"?>
        <!ELEMENT effect_pedal_catalogue (effect_pedal+)>
        <!ELEMENT effect_pedal (image, name, type, year_of_manufacturing, price, power, dimensions, weight, true_bypass, description)>
        <!ELEMENT image (#PCDATA)>
        <!ELEMENT name (manufacturer_name, model_name)>
        <!ELEMENT manufacturer_name (#PCDATA)>
        <!ELEMENT model_name (#PCDATA)>
        <!ELEMENT type (#PCDATA)>
        <!ELEMENT year_of_manufacturing (#PCDATA)>
        <!ELEMENT price (#PCDATA)>
        <!ELEMENT power (polarity, voltage, current_draw, battery)>
        <!ELEMENT polarity (#PCDATA)>
        <!ELEMENT voltage (#PCDATA)>
        <!ELEMENT current_draw (#PCDATA)>
        <!ELEMENT battery (#PCDATA)>
        <!ELEMENT dimensions (width, height, length)>
        <!ELEMENT width (#PCDATA)>
        <!ELEMENT height (#PCDATA)>
        <!ELEMENT length (#PCDATA)>
        <!ELEMENT weight (#PCDATA)>
        <!ELEMENT true_bypass (#PCDATA)>
        <!ELEMENT description (text)>
        <!ELEMENT text (#PCDATA)>

        <!ATTLIST effect_pedal analog_or_digital (Digital|Analog) #IMPLIED>
        <!ATTLIST price currency CDATA #REQUIRED>
        <!ATTLIST battery has (Да|Не) #IMPLIED>
        <!ATTLIST width unit CDATA #REQUIRED>
        <!ATTLIST height unit CDATA #REQUIRED>
        <!ATTLIST length unit CDATA #REQUIRED>
        <!ATTLIST weight unit CDATA #REQUIRED>
        <!ATTLIST true_bypass has (Да|Не) #IMPLIED>

=== volen17/XML-Project-Effect-Pedals/jhs_plain_text.xml
<?xml version="1.0" encoding="utf-8"?>
<?xml-stylesheet type="text/xsl" href="jhs_plain_text.xsl"?>

<!DOCTYPE effect_pedal_catalogue SYSTEM "effect_pedal_catalogue.dtd">

<effect_pedal_catalogue>
    <effect_pedal analog_or_digital="Analog">
        <image>jhs.jpg</image>
        <name>
            <manufacturer_name>JHS</manufacturer_name>
            <model_name>Unicorn V2</model_name>
        </name>
        <type>Bulb Driven Uni-vibe</type>
        <year_of_manufacturing>2018</year_of_manufacturing>
        <price currency="лв.">528.92</price>
        <power>
            <polarity>- в средата</polarity>
            <voltage>9 DC</voltage>
            <current_draw>100mA</current_draw>
            <battery has="Не"/>
        </power>
        <dimensions>
            <width unit="см">5,6</width>
            <height unit="см">4,1</height>
            <length unit="см">12,1</length>
        </dimensions>
        <weight unit="гр">290</weight>
        <true_bypass has="Да"/>
        <description>
            <text>
                Звънлива модулация, странен вътрешен и външен phaser, шеметни ротационни звуци – всички тези легендарни ефекти са натъпкани в Unicorn V2. Трябва да изслушате Star Spangled Banner на Хендрикс или Breathe на Pink Floyd, за да получите представа за необичайните звуци, които може да издава това митично създание.
            </text>
        </description>
    </effect_pedal>
</effect_pedal_catalogue>

=== volen17/XML-Project-Effect-Pedals/overdrives_html.xml
<?xml version="1.0"?>
<?xml-stylesheet type="text/xsl" href="overdrives_html.xsl"?>

<!DOCTYPE effect_pedal_catalogue SYSTEM "effect_pedal_catalogue.dtd">

<effect_pedal_catalogue>
    <effect_pedal analog_or_digital="Analog">
        <image>lightspeed.jpg</image>
        <name>
            <manufacturer_name>Greer Amps</manufacturer_name>
            <model_name>Lightspeed</model_name>
        </name>
        <type>Organic Overdrive</type>
        <year_of_manufacturing>2018</year_of_manufacturing>
        <price currency="лв.">435.18</price>
        <power>
            <polarity>- в средата</polarity>
            <voltage>9 DC</voltage>
            <current_draw>11mA</current_draw>
            <battery has="Да" />
        </power>
        <dimensions>
            <width unit="см">6,7</width>
            <height unit="см">5,5</height>
            <length unit="см">12</length>
        </dimensions>
        <weight unit="гр">268</weight>
        <true_bypass has="Да" />
        <description>
            <text>
                Lightspeed е един от най-популярните педали от усилвателите на Greer и с добра причина! Звучи невероятно. Това е прозрачен овърдрайв, който е създаден специално да запази органичния звук на вашата китара, без да променя тоналността твърде много. Въпреки това, може да се настрои да „оцветява“ звука малко повече и да изтласка чист усилвател над ръба или да добави сладък състейн към вече крънчи канал.
            </text>
        </description>
    </effect_pedal>
    <effect_pedal analog_or_digital="Analog">
        <image>vemuram.jpg</image>
        <name>
            <manufacturer_name>Vemuram</manufacturer_name>
            <model_name>Jan Ray</model_name>
        </name>
        <type>Overdrive</type>
        <year_of_manufacturing>2017</year_of_manufacturing>
        <price currency="лв.">844.49</price>
        <power>
            <polarity>- в средата</polarity>
            <voltage>9 DC</voltage>
            <current_draw>5mA</current_draw>
            <battery has="Да" />
        </power>
        <dimensions>
            <width unit="см">7</width>
            <height unit="см">5</height>
            <length unit="см">11,2</length>
        </dimensions>
        <weight unit="гр">428</weight>
        <true_bypass has="Да" />
        <description>
            <text>
                Jan Ray е проектиран да пресъздаде ударния ясен тон на усилвателите Blackface Fender от 60-те - така нареченият звук "Fender Magic 6". Лесен за управление овърдрайв, запазващ характеристиките на китарата със страхотен състейн без неестествена компресия.
            </text>
        </description>
    </effect_pedal>
</effect_pedal_catalogue>

=== volen17/XML-Project-Effect-Pedals/reverbs_html.xml
<?xml version="1.0"?>
<?xml-stylesheet type="text/xsl" href="reverbs_html.xsl"?>

<!DOCTYPE effect_pedal_catalogue SYSTEM "effect_pedal_catalogue.dtd">

<effect_pedal_catalogue>
    <effect_pedal analog_or_digital="Digital">
        <image>bigsky.jpg</image>
        <name>
            <manufacturer_name>Strymon</manufacturer_name>
            <model_name>BigSky</model_name>
        </name>
        <type>Multidimensional Reverb</type>
        <year_of_manufacturing>2016</year_of_manufacturing>
        <price currency="лв.">1056.20</price>
        <power>
            <polarity>- в средата</polarity>
            <voltage>9 DC</voltage>
            <current_draw>300mA</current_draw>
            <battery has="Не"/>
        </power>
        <dimensions>
            <width unit="см">17,5</width>
            <height unit="см">5</height>
            <length unit="см">12,7</length>
        </dimensions>
        <weight unit="гр">907</weight>
        <true_bypass has="Да"/>
        <description>
            <text>
                Strymon се превърнаха в определящите тенденции за мощни, цифрово управлявани педали с множество ефекти. Big Sky е едно от техните водещи предложения; всеобхватна реверберационна единица, която ви позволява да постигнете практически всеки възможен реверберационен звук.
            </text>
        </description>
    </effect_pedal>
</effect_pedal_catalogue>

=== volen17/XML-Project-Effect-Pedals/polytune_xml.xml
<?xml version="1.0" encoding="utf-8"?>
<?xml-stylesheet type="text/xsl" href="polytune_xml.xsl"?>

<!DOCTYPE effect_pedal_catalogue SYSTEM "effect_pedal_catalogue.dtd">

<effect_pedal_catalogue>
    <effect_pedal analog_or_digital="Digital">
        <image>polytune.jpg</image>
        <name>
            <manufacturer_name>TC Electronic</manufacturer_name>
            <model_name>Polytune 3 Mini</model_name>
        </name>
        <type>Tuner</type>
        <year_of_manufacturing>2019</year_of_manufacturing>
        <price currency="лв.">176.31</price>
        <power>
            <polarity>- в средата</polarity>
            <voltage>9 DC</voltage>
            <current_draw>100mA</current_draw>
            <battery has="Не"/>
        </power>
        <dimensions>
            <width unit="см">5,1</width>
            <height unit="см">4,5</height>
            <length unit="см">9,3</length>
        </dimensions>
        <weight unit="гр">160</weight>
        <true_bypass has="Да"/>
        <description>
            <text>
                Компактният, бърз и точен тунер е основата на вашия педалборд. TC Electronic Polytune 3 Mini отвежда нещата по-далеч с вградения Bonafide буфер, за да поддържа вашия тон чист.
            </text>
        </description>
    </effect_pedal>
</effect_pedal_catalogue>
